#!/bin/bash

################################################################################
# Help                                                                         #
################################################################################
Help()
{
    echo
    echo "Blackfire Toolkit"
    echo
    echo "Syntax: scriptTemplate [-h|on|off|clean]"
    echo "Options:"
    echo "on         Enable Blackfire."
    echo "off        Disable Blackfire."
    echo
}

################################################################################
# Main                                                                         #
################################################################################
Main(){
    echo
    echo "Blackfire Toolkit"
    echo
    echo "-h               This help"
}

# Get the options
while getopts ":h" option; do
   case $option in
      h) # display Help
         Help
         exit;;
     \?) # incorrect option
         echo "Error: Invalid option"
         exit;;
   esac
done

echo
read -p "Enter mode: " VAR1

# OPCache mode
ON="on"
OFF="off"

if [[ "$VAR1" = "$ON" ]]; then
    cp /tmp/blackfire.ini /usr/local/etc/php/conf.d/ && kill -USR2 1 && echo "Enable Blackfire was completed."
elif [[ "$VAR1" = "$OFF" ]]; then
    mv /usr/local/etc/php/conf.d/blackfire.ini /tmp/ && kill -USR2 1 && echo "Disable Blackfire was completed."
else
    echo
    echo "Error: Invalid option"
    Main
fi