#!/bin/bash

################################################################################
# Help                                                                         #
################################################################################
HELP()
{
    echo
    echo "OPCache Toolkit"
    echo
    echo "Syntax: scriptTemplate [-h|on|off|clean]"
    echo "Options:"
    echo "on         Enable OPCache."
    echo "off        Disable OPCache."
    echo "clean      Clean OPCache."
    echo
}

################################################################################
# Main                                                                         #
################################################################################
MAIN(){
    echo
    echo "OPCache Toolkit"
    echo
    echo "-h               This help"
}

ENABLE() {
    cp /tmp/docker-php-ext-opcache.ini /usr/local/etc/php/conf.d/ \
    && kill -USR2 1 \
    && echo "Enable OPCache was completed."
}

DISABLE() {
        mv /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini /tmp/ \
    && kill -USR2 1 \
    && echo "Disable OPCache was completed."
}

CLEAN() {
    kill -USR2 1 && echo "Clean OPCache was completed."
}

################################################################################
# Options                                                                      #
################################################################################
while getopts ":h" option; do
   case $option in
      h) # display Help
         HELP
         exit;;
   esac
done

case $1 in
  "on") ENABLE ;;
  "off") DISABLE ;;
  "clean") CLEAN ;;
   *) MAIN ;;
esac