#!/bin/bash

################################################################################
# Help                                                                         #
################################################################################
HELP()
{
    echo
    echo "XDebug Toolkit"
    echo
    echo "Syntax: scriptTemplate [-h|on|off]"
    echo "Options:"
    echo "on         Enable xdebug."
    echo "off        Disable xdebug."
    echo
}

################################################################################
# Main                                                                         #
################################################################################
MAIN(){
    echo
    echo "XDebug Toolkit"
    echo
    echo "-h               This help"
}

ENABLE() {
    opcache off \
    && cp /tmp/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/ \
    && kill -USR2 1 \
    && echo "Enable xdebug was completed."
}

DISABLE() {
    rm -rf /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && kill -USR2 1 \
    && echo "Disable xdebug was completed."
}

################################################################################
# Options                                                                      #
################################################################################
while getopts ":h" option; do
   case $option in
    h) # display Help
        HELP
        exit;;
   esac
done

case $1 in
  "on") ENABLE ;;
  "off") DISABLE ;;
   *) MAIN ;;
esac