#!/bin/bash

sed -i \
-e "s/newrelic.license[[:space:]]*=[[:space:]]*.*/newrelic.license = ${NEW_RELIC_LICENSE_KEY}/" \
-e "s/newrelic.appname[[:space:]]*=[[:space:]]*.*/newrelic.appname = ${NEW_RELIC_APPNAME}/" \
-e "\$a newrelic.daemon.address=newrelic-php-daemon:31339" \
/usr/local/etc/php/conf.d/newrelic.ini
